### PR TITLE
[cli] new: Link to GitHub dependencies instead of using relative paths

### PR DESCRIPTION
**Pull request by shawntabrizi**

### CODE REVIEW

**Comment by Robbepop** [comment]
nice!

could you please prepend the commit with `[cli]` since it is concerned with the pDSL CLI project.
I should have written a contribution guideline finally.

**Comment by shawntabrizi** [comment]
Just the title? Or the commit itself?

**Comment by Robbepop** [comment]
> Just the title? Or the commit itself?

It is about the commit itself. Part of the unwritten commit guidelines.
Btw.: I've uploaded the contribution guidelines. :) You can find them [here](https://github.com/Robbepop/pdsl/blob/master/CONTRIBUTING.md).

**Comment by Robbepop** [comment]
lgtm!

**Pull request merged**
